<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Meta-analysis of prognostic factors • metamisc</title>
<script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="ma-pf_files/libs/quarto-html/popper.min.js"></script><script src="ma-pf_files/libs/quarto-html/tippy.umd.min.js"></script><link href="ma-pf_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ma-pf_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
<!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Meta-analysis of prognostic factors">
<meta property="og:image" content="https://smartdata-analysis-and-statistics.github.io/metamisc/logo.png">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">metamisc</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.5.0</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/ma-pf.html">Meta-analysis of prognostic factors</a></li>
    <li><a class="dropdown-item" href="../articles/ma-pm.html">Meta-analysis of prediction model performance</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/smartdata-analysis-and-statistics/metamisc/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Meta-analysis of prognostic factors</h1>

      <p class="author">Thomas Debray</p>
      <p class="date">Last Updated on 23 September, 2025</p>

      <small class="dont-index">Source: <a href="https://github.com/smartdata-analysis-and-statistics/metamisc/blob/main/vignettes/ma-pf.qmd" class="external-link"><code>vignettes/ma-pf.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <section class="section level2" data-number="1"><h2 data-number="1" id="introduction">
<span class="header-section-number">1</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction"></a>
</h2>
<p>An important task in medical research is the identification and assessment of prognostic factors. A prognostic factor is any measure that, among people with a given health condition (that is, a startpoint), is associated with a subsequent clinical outcome (an endpoint) <span class="citation" data-cites="riley_prognosis_2013">(<a href="#ref-riley_prognosis_2013" role="doc-biblioref">Riley 2013</a>)</span>. Commonly investigated prognostic factors include simple measures such as age, sex, and size of tumor, but they can also include more complex factors such as abnormal levels of proteins or catecholamines and unusual genetic mutations <span class="citation" data-cites="sauerbrei_evidence-based_2006">(<a href="#ref-sauerbrei_evidence-based_2006" role="doc-biblioref">Sauerbrei and Altman 2006</a>)</span>. They can be useful as modifiable targets for interventions to improve outcomes, building blocks for prognostic models, or predictors of differential treatment response.</p>
<p>Over the past few decades, numerous prognostic factor studies have been published in the medical literature. For example, <span class="citation" data-cites="riley_reporting_2003">Riley and Burchill (<a href="#ref-riley_reporting_2003" role="doc-biblioref">2003</a>)</span> identified 260 studies reporting associations for 130 different tumour markers for neuroblastoma. More recently, <span class="citation" data-cites="tzoulaki_assessment_2009">Tzoulaki and Ioannidis (<a href="#ref-tzoulaki_assessment_2009" role="doc-biblioref">2009</a>)</span> identified 79 studies reporting the added value of 86 different markers when added to the Framingham risk score. Despite this huge research effort, the prognostic value of most traditional factors under discussion is uncertain and the usefulness of many specific markers, prognostic indices, and classification schemes is still unproven <span class="citation" data-cites="sauerbrei_evidence-based_2006">(<a href="#ref-sauerbrei_evidence-based_2006" role="doc-biblioref">Sauerbrei and Altman 2006</a>)</span>.</p>
<p>The aim of this introduction is to illustrate how to summarize the results from multiple prognostic factor studies and how to investigate sources of between-study heterogeneity.</p>
<p>In this practical we will make use of the R packages <code>metamisc</code> and <code>metafor</code>. The <a href="metafor">https://cran.r-project.org/package=metafor</a> package provides a comprehensive collection of functions for conducting meta-analyses in R. The <a href="metamisc">https://cran.r-project.org/package=metamisc</a> package provides additional functions to facilitate meta-analysis of prognosis studies. We can load these packages as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://www.metafor-project.org" class="external-link">metafor</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/smartdata-analysis-and-statistics/metamisc" class="external-link">metamisc</a></span><span class="op">)</span></span></code></pre></div>
</div>
</section><section class="section level2" data-number="2"><h2 data-number="2" id="meta-analysis-of-prognostic-effect-estimates">
<span class="header-section-number">2</span> Meta-analysis of prognostic effect estimates<a class="anchor" aria-label="anchor" href="#meta-analysis-of-prognostic-effect-estimates"></a>
</h2>
<section class="level2" data-number="2.1"><h3 data-number="2.1" id="background-information">
<span class="header-section-number">2.1</span> Background information<a class="anchor" aria-label="anchor" href="#background-information"></a>
</h3>
<p>Endometrial cancer (EC) is the fourth most common malignancy in women and the most common gynecologic cancer. Overall, the 5-year survival rates for EC are approximately 78–90% for stage I, 74% for stage II, 36–57% for stage III, and 20% for stage IV. Such poor outcomes raise an urgent requirement that more accurate prognosis and predictive markers should be applied for EC to guide the therapy and monitor the disease progress for individual patients.</p>
<p>Several biological molecules have been proposed as prognostic biomarkers in EC. Among them, hormone receptors such as estrogen receptors (ER), progesterone receptors (PR), and human epidermal growth factor receptor 2 (HER2) are attractive because of their physiological functions. Recently, Zhang conducted a systematic review to evaluate the overall risk of these hormone receptors for endometrial cancer survival <span class="citation" data-cites="zhang_prognostic_2015">(<a href="#ref-zhang_prognostic_2015" role="doc-biblioref">Zhang and Sun 2015</a>)</span>. This review included 16 studies recruiting 1764 patients for HER2. We can load the data from all 16 studies in R as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">)</span></span></code></pre></div>
</div>
<p>This creates an object <code>Zhang</code> that contains the summary data from 14 studies reporting on overall survival (OS) and from 6 studies reporting on progression-free survival (PFS). As a result, a total of 20 estimates are available for the hazard ratio of HER2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Zhang</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Study    PrimaryAuthor year     Country Disease   N    HR
1  Gonzalez-Rodilla 2013 Gonzalez-Rodilla 2013       Spain      EC 126  1.14
2            Togami 2012           Togami 2012       Japan    UPSC  71  3.00
3              Mori 2010             Mori 2010       Japan     EEC  63  2.58
4          Jongen 2009-2           Jongen 2009 Netherlands     EEC 315  0.66
5           Konecny 2009          Konecny 2009         USA      EC 273  2.13
6           Odicino 2008          Odicino 2008       Italy    UPSC  10  1.60
7          Santin 2005-2           Santin 2005         USA    UPSC  30  5.19
8          Santin 2005-1           Santin 2005         USA    UPSC  27 12.43
9             Backe 1997            Backe 1997     Germany      EC 222  1.17
10       Kohlberger 1996       Kohlberger 1996   Australia      EC 100  3.95
11          Saffari 2995          Saffari 1995         USA      EC  75  5.25
12            Peiro 2004            Peiro 2004     Germany      EC  10  1.64
13       Cianciulli 2003       Cianciulli 2003       Italy      EC  73  1.90
14            Gates 2006            Gates 2006         USA      EC  99  4.00
15           Togami 2012           Togami 2012       Japan    UPSC  71  3.43
16             Mori 2010             Mori 2010       Japan     EEC  63  3.80
17         Jongen 2009-2           Jongen 2009 Netherlands     EEC 315  1.75
18         Coronado 2001         Coronado 2001       Spain      EC 114  2.69
19            Backe 1997            Backe 1997     Germany      EC 222  1.36
20             Voss 2011              Vos 2011     England      EC 156  1.41
   HR.025 HR.975 outcome
1    0.52   2.52      OS
2    1.15   7.01      OS
3    1.03   7.92      OS
4    0.10   4.28      OS
5    1.65   2.73      OS
6    0.89   2.89      OS
7    1.52  17.64      OS
8    1.57  98.28      OS
9    0.93   1.49      OS
10   1.07  14.69      OS
11   1.33  20.74      OS
12   1.04   2.57      OS
13   0.83   4.36      OS
14   0.77  20.80      OS
15   1.50   7.23     PFS
16   1.29  12.35     PFS
17   0.23  13.08     PFS
18   1.35   5.37     PFS
19   0.65   2.85     PFS
20   0.51   3.88     PFS</code></pre>
</div>
</div>
<p>For each study, estimates of effect were retrieved as follows. The simplest method consisted in the direct collection of HR, odds ratio or risk ratio, and their 95% CI from the original article, with an HR of less than 1 being associated with a better outcome. If not available, the total numbers of observed deaths/cancer recurrences and the numbers of patients in each group were extracted to calculate HR. When data were only available as Kaplan-Meier curves, data were extracted from the graphical survival plots, and estimation of the HR was then performed using the described method.</p>
<p>A total of 14 studies assessed the relation between HER2 and overall survival. The corresponding hazard ratios (HR) are given below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Zhang</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Study    PrimaryAuthor year     Country Disease   N    HR
1  Gonzalez-Rodilla 2013 Gonzalez-Rodilla 2013       Spain      EC 126  1.14
2            Togami 2012           Togami 2012       Japan    UPSC  71  3.00
3              Mori 2010             Mori 2010       Japan     EEC  63  2.58
4          Jongen 2009-2           Jongen 2009 Netherlands     EEC 315  0.66
5           Konecny 2009          Konecny 2009         USA      EC 273  2.13
6           Odicino 2008          Odicino 2008       Italy    UPSC  10  1.60
7          Santin 2005-2           Santin 2005         USA    UPSC  30  5.19
8          Santin 2005-1           Santin 2005         USA    UPSC  27 12.43
9             Backe 1997            Backe 1997     Germany      EC 222  1.17
10       Kohlberger 1996       Kohlberger 1996   Australia      EC 100  3.95
11          Saffari 2995          Saffari 1995         USA      EC  75  5.25
12            Peiro 2004            Peiro 2004     Germany      EC  10  1.64
13       Cianciulli 2003       Cianciulli 2003       Italy      EC  73  1.90
14            Gates 2006            Gates 2006         USA      EC  99  4.00
15           Togami 2012           Togami 2012       Japan    UPSC  71  3.43
16             Mori 2010             Mori 2010       Japan     EEC  63  3.80
17         Jongen 2009-2           Jongen 2009 Netherlands     EEC 315  1.75
18         Coronado 2001         Coronado 2001       Spain      EC 114  2.69
19            Backe 1997            Backe 1997     Germany      EC 222  1.36
20             Voss 2011              Vos 2011     England      EC 156  1.41
   HR.025 HR.975 outcome
1    0.52   2.52      OS
2    1.15   7.01      OS
3    1.03   7.92      OS
4    0.10   4.28      OS
5    1.65   2.73      OS
6    0.89   2.89      OS
7    1.52  17.64      OS
8    1.57  98.28      OS
9    0.93   1.49      OS
10   1.07  14.69      OS
11   1.33  20.74      OS
12   1.04   2.57      OS
13   0.83   4.36      OS
14   0.77  20.80      OS
15   1.50   7.23     PFS
16   1.29  12.35     PFS
17   0.23  13.08     PFS
18   1.35   5.37     PFS
19   0.65   2.85     PFS
20   0.51   3.88     PFS</code></pre>
</div>
</div>
<p>EEC endometrioid endometrial cancer, UPSC uterine papillary serous carcinoma</p>
<p>The hormone receptor HER2 has prognostic value for survival but is prone to substantial between-study heterogeneity. Hazard ratios appear much larger for studies conducted in the USA</p>
<p>The heterogeneity of the population was probably due to the difference in the baseline characteristics of patients (age, tumor stage, race, methodology for assessing HRs expression, or country), the cutoff value of markers, the undergoing treatment, the duration of follow-up, and others. Also, HRs are unadjusted, and therefore highly prone to heterogeneity in patient spectrum.</p>
<p>Note that the total number of studies is indeed 16:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">Study</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
</div>
</section><section class="level2" data-number="2.2"><h3 data-number="2.2" id="exploratory-analyses">
<span class="header-section-number">2.2</span> Exploratory analyses<a class="anchor" aria-label="anchor" href="#exploratory-analyses"></a>
</h3>
<p>It is often helpful to display the effect sizes of all studies in a forest plot. The forest plot for overall survival can then be generated as follows. Briefly, we here provide information on the estimated hazard ratios (via the argument <code>theta</code>), as well as the bounds of their 95% confidence interval (via <code>theta.ci.lb</code> and <code>theta.ci.ub</code>). Further, we only include the 14 estimates for overall survival.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Zhang</span>, <span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">ds</span>, <span class="fu"><a href="../reference/forest.html">forest</a></span><span class="op">(</span>theta <span class="op">=</span> <span class="va">HR</span>, theta.ci.lb <span class="op">=</span> <span class="va">HR.025</span>, theta.ci.ub <span class="op">=</span> <span class="va">HR.975</span>, </span>
<span>                theta.slab <span class="op">=</span> <span class="va">Study</span>, xlab <span class="op">=</span> <span class="st">"Hazard ratio of HER2 versus OS"</span>, refline <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<p>We can also generate the same plot using <code>metafor</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">metafor</span><span class="fu">::</span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/forest.html" class="external-link">forest</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">HR</span>, ci.lb <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">HR.025</span>, ci.ub <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">HR.975</span>, slab <span class="op">=</span> </span>
<span>                  <span class="va">Zhang</span><span class="op">$</span><span class="va">Study</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span>,  xlab <span class="op">=</span> </span>
<span>                  <span class="st">"Hazard ratio of HER2 versus OS"</span>, refline <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="ma-pf_files/figure-html/unnamed-chunk-7-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is easier to assess the summary effect and the presence of statistical heterogeneity.</p>
</section><section class="level2" data-number="2.3"><h3 data-number="2.3" id="data-preparation">
<span class="header-section-number">2.3</span> Data preparation<a class="anchor" aria-label="anchor" href="#data-preparation"></a>
</h3>
<p>To facilitate any further analysis, information on the standard error of the different study effect sizes is needed. Estimates for the standard error can be obtained from the reported 95% confidence intervals <span class="citation" data-cites="altman_how_2011">(<a href="#ref-altman_how_2011" role="doc-biblioref">Altman Douglas G. and Bland 2011</a>)</span>. However, rather than estimating the standard error of the HR, we will calculate the log HR and estimate its corresponding standard error. The main reason is that the HR is a ratio measure, for which the (within-study) sampling variation can be approximated with a Normal distribution if the log scale is used.</p>
<p>The standard error (SE) of the log hazard ratio is simply given as:</p>
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mrow><mi mathvariant="normal">S</mi><mi mathvariant="normal">E</mi></mrow><mo>=</mo><mrow><mo stretchy="true" form="prefix">(</mo><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><mi>u</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo>−</mo><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><mi>l</mi><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="true" form="postfix">)</mo></mrow><mi>/</mi><mrow><mo stretchy="true" form="prefix">(</mo><mn>2</mn><mo>*</mo><mn>1.96</mn><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\mathrm{SE}=(\log(u)-\log(l))/(2*1.96)</annotation></semantics></math></p>
<p>where the upper and lower limits of the 95% CI are <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>u</mi><annotation encoding="application/x-tex">u</annotation></semantics></math> and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>l</mi><annotation encoding="application/x-tex">l</annotation></semantics></math> respectively. In <code>R</code>, we have:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Zhang</span><span class="op">$</span><span class="va">logHR</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">HR</span><span class="op">)</span></span>
<span><span class="va">Zhang</span><span class="op">$</span><span class="va">se.logHR</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">HR.975</span><span class="op">)</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">HR.025</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="fl">2</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html" class="external-link">qnorm</a></span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fl">0.05</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Study    PrimaryAuthor year     Country Disease   N   HR
1 Gonzalez-Rodilla 2013 Gonzalez-Rodilla 2013       Spain      EC 126 1.14
2           Togami 2012           Togami 2012       Japan    UPSC  71 3.00
3             Mori 2010             Mori 2010       Japan     EEC  63 2.58
4         Jongen 2009-2           Jongen 2009 Netherlands     EEC 315 0.66
5          Konecny 2009          Konecny 2009         USA      EC 273 2.13
6          Odicino 2008          Odicino 2008       Italy    UPSC  10 1.60
  HR.025 HR.975 outcome      logHR  se.logHR
1   0.52   2.52      OS  0.1310283 0.4026057
2   1.15   7.01      OS  1.0986123 0.4611247
3   1.03   7.92      OS  0.9477894 0.5203750
4   0.10   4.28      OS -0.4155154 0.9583181
5   1.65   2.73      OS  0.7561220 0.1284530
6   0.89   2.89      OS  0.4700036 0.3004622</code></pre>
</div>
</div>
</section><section class="level2" data-number="2.4"><h3 data-number="2.4" id="assessment-of-publication-bias">
<span class="header-section-number">2.4</span> Assessment of publication bias<a class="anchor" aria-label="anchor" href="#assessment-of-publication-bias"></a>
</h3>
<p>The presence of small-study effects is a common threat to systematic reviews and meta-analyses. Small-study effects is a generic term for the phenomenon that sometimes smaller studies show different, often stronger, effects than the large ones <span class="citation" data-cites="debray_detecting_2018">(<a href="#ref-debray_detecting_2018" role="doc-biblioref">Debray and Riley 2018</a>)</span>. One possible reason is publication bias. Previously, <span class="citation" data-cites="altman_systematic_2001">D. G. Altman (<a href="#ref-altman_systematic_2001" role="doc-biblioref">2001</a>)</span> argued that it is probable that studies showing a strong (often statistically significant) prognostic ability are more likely to be published. For this reason, it is important to evaluate the potential presence of small-study effects, which can be verified by visual inspection of the funnel plot. In this plot, the estimate of the reported effect size is plotted against a measure of precision or sample size for each included study of the meta-analysis. The premise is that the scatter of plots should reflect a funnel shape, if small-study effects do not exist (provided that effect sizes are not substantially affected by the presence of between-study heterogeneity). However, when small studies are predominately in one direction (usually the direction of larger effect sizes), asymmetry will ensue.</p>
<p>A common approach to construct the funnel plot is to display the individual observed effect sizes on the x-axis against the corresponding standard errors on the y-axis, and to use the fixed effect summary estimate as reference value. In the absence of publication bias and heterogeneity, one would then expect to see the points forming a funnel shape, with the majority of the points falling inside of the pseudo-confidence region of the summary estimate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">res</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html" class="external-link">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">logHR</span>, sei <span class="op">=</span> <span class="va">se.logHR</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span>, method <span class="op">=</span> <span class="st">"FE"</span>, data <span class="op">=</span> <span class="va">Zhang</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/funnel.html" class="external-link">funnel</a></span><span class="op">(</span><span class="va">res</span>, xlab<span class="op">=</span><span class="st">"Log Hazard Ratio"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="ma-pf_files/figure-html/unnamed-chunk-9-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Most study estimates fall within the pseudo-confidence region, hence there appears limited evidence for publication bias.</p>
<p>We can formally test the presence of asymmetry in the funnel plot by evaluating whether there is an association between the estimated standard error and the estimated effect size.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/regtest.html" class="external-link">regtest</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">logHR</span>, sei <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">se.logHR</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span>, </span>
<span>        model <span class="op">=</span> <span class="st">"lm"</span>, predictor <span class="op">=</span> <span class="st">"sei"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     weighted regression with multiplicative dispersion
Predictor: standard error

Test for Funnel Plot Asymmetry: t = 2.1622, df = 12, p = 0.0515
Limit Estimate (as sei -&gt; 0):   b = 0.2590 (CI: -0.0760, 0.5939)</code></pre>
</div>
</div>
<p>The P-value for funnel plot asymmetry is given as 0.052. Note that it is common to use a 10% level of significance because the number of studies in a meta-analysis is usually low and also there is evidence for funnel plot asymmetry, as the P-value is below 0.10.</p>
<p>Funnel plot asymmetry tests can also be performed using <a href="https://cran.r-project.org/package=metamisc" class="external-link">metamisc</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Zhang</span>, <span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span></span>
<span><span class="va">regfit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">ds</span>, <span class="fu"><a href="../reference/fat.html">fat</a></span><span class="op">(</span>b<span class="op">=</span><span class="va">logHR</span>, b.se<span class="op">=</span><span class="va">se.logHR</span>, method<span class="op">=</span><span class="st">"E-FIV"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">regfit</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: fat(b = logHR, b.se = se.logHR, method = "E-FIV")

Fixed effect summary estimate:  0.5193

test for funnel plot asymmetry: t =2.1622, df = 12, p = 0.0515</code></pre>
</div>
</div>
<p>Again, we can construct a funnel plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">regfit</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="ma-pf_files/figure-html/unnamed-chunk-13-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Some caution is warranted when interpreting the results for funnel plot asymmetry tests <span class="citation" data-cites="debray_detecting_2018">(<a href="#ref-debray_detecting_2018" role="doc-biblioref">Debray and Riley 2018</a>)</span>. First, the power to detect asymmetry is often limited because meta-analyses usually do not include many studies. Second, many tests are known to yield inadequate type-I error rates or to suffer from low power. For instance, it has been demonstrated that aforementioned test to evaluate the association between the estimated standard error and effect size tends to yield type-I error rates that are too high. Finally, funnel plot asymmetry may rather be caused by heterogeneity than by publication bias.</p>
<p>Adjust aformentioned regression test to use inverse of the total sample size (rather than the standard error) as predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/regtest.html" class="external-link">regtest</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">logHR</span>, sei <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">se.logHR</span>, ni <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">N</span>, </span>
<span>        subset <span class="op">=</span> <span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span>, model <span class="op">=</span> <span class="st">"lm"</span>, </span>
<span>        predictor <span class="op">=</span> <span class="st">"ninv"</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     weighted regression with multiplicative dispersion
Predictor: inverse of the sample size

Test for Funnel Plot Asymmetry: t = 0.1552, df = 12, p = 0.8793
Limit Estimate (as ni -&gt; inf):  b = 0.5088 (CI: 0.2226, 0.7950)</code></pre>
</div>
</div>
<p>From here onwards, we will assume that the potential for publication bias is neglegible, and proceed with standard meta-analysis methods.</p>
</section><section class="level2" data-number="2.5"><h3 data-number="2.5" id="meta-analysis-of-the-prognostic-value-of-her2">
<span class="header-section-number">2.5</span> Meta-analysis of the prognostic value of HER2<a class="anchor" aria-label="anchor" href="#meta-analysis-of-the-prognostic-value-of-her2"></a>
</h3>
<p>Meta-analysis is an option when the identified studies are considered sufficiently robust and comparable, and requires there are at least two estimates of the same statistic across studies. A random effects approach is often essential to allow for unexplained heterogeneity across studies due to differences in their methods, time-scale, populations, cut-points, adjustment factors, and treatments.</p>
<p>A standard random effects meta-analysis combines the study estimates of the statistic of interest (here given as the log HR of HER2) in order to estimate the average effect (denoted by <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>μ</mi><annotation encoding="application/x-tex">\mu</annotation></semantics></math>) and its standard deviation (denoted by <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>τ</mi><annotation encoding="application/x-tex">\tau</annotation></semantics></math>) across studies. If <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mover><mi>b</mi><mo accent="true">̂</mo></mover><mi>i</mi></msub><annotation encoding="application/x-tex">\hat b_i</annotation></semantics></math> and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mrow><mi mathvariant="normal">v</mi><mi mathvariant="normal">a</mi><mi mathvariant="normal">r</mi></mrow><mrow><mo stretchy="true" form="prefix">(</mo><msub><mover><mi>b</mi><mo accent="true">̂</mo></mover><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\mathrm{var}(\hat b_i)</annotation></semantics></math> denote the estimate and its variance in study <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>i</mi><annotation encoding="application/x-tex">i</annotation></semantics></math>, then a general random effects meta-analysis model can be specified as:</p>
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mover><mi>b</mi><mo accent="true">̂</mo></mover><mi>i</mi></msub><mo>∼</mo><mi>N</mi><mrow><mo stretchy="true" form="prefix">(</mo><mi>μ</mi><mo>,</mo><mrow><mi mathvariant="normal">v</mi><mi mathvariant="normal">a</mi><mi mathvariant="normal">r</mi></mrow><mrow><mo stretchy="true" form="prefix">(</mo><msub><mover><mi>b</mi><mo accent="true">̂</mo></mover><mi>i</mi></msub><mo stretchy="true" form="postfix">)</mo></mrow><mo>+</mo><msup><mi>τ</mi><mn>2</mn></msup><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">\hat b_i \sim N(\mu, \mathrm{var}(\hat b_i) + \tau^2)</annotation></semantics></math></p>
<p>It is common to first estimate the heterogeneity parameter <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>τ</mi><annotation encoding="application/x-tex">\tau</annotation></semantics></math> and to use the resulting value to estimate <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>μ</mi><annotation encoding="application/x-tex">\mu</annotation></semantics></math>. However, such approach does not adequately reflect the error associated with parameter estimation, especially when the number of studies is small. For this reason, alternative estimators have been proposed that simultaneously estimate <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>μ</mi><annotation encoding="application/x-tex">\mu</annotation></semantics></math> and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>τ</mi><annotation encoding="application/x-tex">\tau</annotation></semantics></math>. Here, we will focus on Restricted Maximum Likelihood Estimation (REML), which is implemented as default in <code>metafor</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">resREML</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html" class="external-link">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">logHR</span>, sei <span class="op">=</span> <span class="va">se.logHR</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">outcome</span><span class="op">==</span><span class="st">"OS"</span><span class="op">)</span>, </span>
<span>               method <span class="op">=</span> <span class="st">"REML"</span>, slab <span class="op">=</span> <span class="va">Study</span>, data <span class="op">=</span> <span class="va">Zhang</span><span class="op">)</span></span>
<span><span class="va">resREML</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 14; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0883 (SE = 0.0854)
tau (square root of estimated tau^2 value):      0.2972
I^2 (total heterogeneity / total variability):   49.17%
H^2 (total variability / sampling variability):  1.97

Test for Heterogeneity:
Q(df = 13) = 28.9214, p-val = 0.0067

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub
  0.6669  0.1354  4.9251  &lt;.0001  0.4015  0.9324  ***

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># The following approach yields the same results</span></span>
<span><span class="co"># rma(yi=logHR, sei=se.logHR, subset=(outcome=="OS"), data=Zhang)</span></span></code></pre></div>
</div>
<p>The summary effect size is 0.667 and the between-study standard deviation is 0.297</p>
<p>The standard error of the summary effect size is 0.135 and the standard error of the between-study variance is 0.085</p>
<p>We can calculate the summary HR and the corresponding 95% CI by back-transforming the estimate for <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>μ</mi><annotation encoding="application/x-tex">\mu</annotation></semantics></math> and its confidence bounds:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">b</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
intrcpt 1.948268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">ci.lb</span>, <span class="va">resREML</span><span class="op">$</span><span class="va">ci.ub</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.494104 2.540483</code></pre>
</div>
</div>
<p>Note that the confidence interval for <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>μ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \mu</annotation></semantics></math> is usually based on a Student T distribution to account for estimation error in <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>τ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \tau</annotation></semantics></math>.</p>
<p>The summary HR of HER2 is statistically significant, so the hormone receptor appears to be predictive on average. In particular, an increased level of HER2 was associated with poorer survival, on average.</p>
<p>We can also obtain the summary estimate and 95% CI for the HR of HER2 by simply using the <code>predict</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html" class="external-link">predict</a></span><span class="op">(</span><span class="va">resREML</span>, transf <span class="op">=</span> <span class="va">exp</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   pred  ci.lb  ci.ub  pi.lb  pi.ub
 1.9483 1.4941 2.5405 1.0272 3.6954 </code></pre>
</div>
</div>
<p>Although the summary result (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>μ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \mu</annotation></semantics></math>) is usually the main focus of a meta-analysis, this reflects some average across studies and it may be hard to translate to clinical practice when there is large between-study heterogeneity. We can quantify the impact of between-study heterogeneity by constructing a <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>100</mn><mrow><mo stretchy="true" form="prefix">(</mo><mn>1</mn><mo>−</mo><mi>α</mi><mi>/</mi><mn>2</mn><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">100(1-\alpha/2)</annotation></semantics></math>% prediction interval, which gives the potential true prognostic effect in a new population conditional on the meta-analysis results <span class="citation" data-cites="riley_interpretation_2011">(<a href="#ref-riley_interpretation_2011" role="doc-biblioref">Riley and Deeks 2011</a>)</span>. An approximate prediction interval (PI) is given as follows:</p>
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mover><mi>μ</mi><mo accent="true">̂</mo></mover><mo>±</mo><msub><mi>t</mi><mrow><mi>α</mi><mo>,</mo><mi>N</mi><mo>−</mo><mn>2</mn></mrow></msub><msqrt><mrow><msup><mover><mi>τ</mi><mo accent="true">̂</mo></mover><mn>2</mn></msup><mo>+</mo><msup><mover><mi>σ</mi><mo accent="true">̂</mo></mover><mn>2</mn></msup></mrow></msqrt></mrow><annotation encoding="application/x-tex">\hat \mu \pm t_{\alpha, N-2} \sqrt{\hat \tau^2 + \hat \sigma^2}</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mi>t</mi><mrow><mi>α</mi><mo>,</mo><mi>N</mi><mo>−</mo><mn>2</mn></mrow></msub><annotation encoding="application/x-tex">t_{\alpha, N-2}</annotation></semantics></math> is the <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>100</mn><mrow><mo stretchy="true" form="prefix">(</mo><mn>1</mn><mo>−</mo><mi>α</mi><mi>/</mi><mn>2</mn><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">100(1-\alpha/2)</annotation></semantics></math>% percentile of the t-distribution for <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>N</mi><mo>−</mo><mn>2</mn></mrow><annotation encoding="application/x-tex">N-2</annotation></semantics></math> degrees of freedom, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>N</mi><annotation encoding="application/x-tex">N</annotation></semantics></math> is the number of studies, <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>σ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \sigma</annotation></semantics></math> is the estimated standard error of <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>μ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \mu</annotation></semantics></math>, and <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>τ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \tau</annotation></semantics></math> is the estimated between-study standard deviation. In <code>R</code>, can calculate the approximate 95% PI for <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mover><mi>μ</mi><mo accent="true">̂</mo></mover><annotation encoding="application/x-tex">\hat \mu</annotation></semantics></math> as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">level</span> <span class="op">&lt;-</span> <span class="fl">0.05</span></span>
<span><span class="va">crit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html" class="external-link">qt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">level</span><span class="op">/</span><span class="fl">2</span>, <span class="fl">1</span><span class="op">-</span><span class="op">(</span><span class="va">level</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>, df <span class="op">=</span> <span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">k</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="va">resREML</span><span class="op">$</span><span class="va">b</span></span>
<span><span class="va">tau2</span> <span class="op">&lt;-</span> <span class="va">resREML</span><span class="op">$</span><span class="va">tau2</span></span>
<span><span class="va">sigma2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/vcov.html" class="external-link">vcov</a></span><span class="op">(</span><span class="va">resREML</span><span class="op">)</span></span>
<span><span class="va">mu</span> <span class="op">+</span> <span class="va">crit</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">tau2</span> <span class="op">+</span> <span class="va">sigma2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.04467483  1.37855606</code></pre>
</div>
</div>
<p>The boundaries of the approximate 95% PI are given as 0.956 to 3.969 .</p>
<p>There is substantial heterogeneity in the prognostic value of HER 2 and its usefulness may be very limited in certain populations.</p>
<p>A possible approach to enhance the interpretation of meta-analysis results is to calculate the probability that the prognostic effect of HER 2 will be above some useful value (e.g. a HR &gt; 1.5 for a binary factor, which indicates risk is increased by at least 50%). We can calculate this probability as follows:</p>
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>P</mi><mi>r</mi><mrow><mo stretchy="true" form="prefix">(</mo><mrow><mi mathvariant="normal">H</mi><mi mathvariant="normal">R</mi></mrow><mo>&gt;</mo><mn>1.5</mn><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mi>P</mi><mi>r</mi><mrow><mo stretchy="true" form="prefix">(</mo><mover><mi>μ</mi><mo accent="true">̂</mo></mover><mo>&gt;</mo><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><mn>1.5</mn><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="true" form="postfix">)</mo></mrow><mo>=</mo><mn>1</mn><mo>−</mo><mi>P</mi><mi>r</mi><mrow><mo stretchy="true" form="prefix">(</mo><mover><mi>μ</mi><mo accent="true">̂</mo></mover><mo>≤</mo><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><mn>1.5</mn><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">Pr(\mathrm{HR} &gt; 1.5) = Pr(\hat \mu &gt; \log(1.5)) = 1 - Pr(\hat \mu \leq \log(1.5))</annotation></semantics></math></p>
<p>where <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>P</mi><mi>r</mi><mrow><mo stretchy="true" form="prefix">(</mo><mover><mi>μ</mi><mo accent="true">̂</mo></mover><mo>≤</mo><mo>log</mo><mrow><mo stretchy="true" form="prefix">(</mo><mn>1.5</mn><mo stretchy="true" form="postfix">)</mo></mrow><mo stretchy="true" form="postfix">)</mo></mrow></mrow><annotation encoding="application/x-tex">Pr(\hat \mu \leq \log(1.5))</annotation></semantics></math> is approximated using a scaled Student-<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>t</mi><annotation encoding="application/x-tex">t</annotation></semantics></math> distribution (similar to the calculation of our prediction interval):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html" class="external-link">pt</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="fl">1.5</span><span class="op">)</span> <span class="op">-</span> <span class="va">mu</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">tau2</span><span class="op">+</span><span class="va">sigma2</span><span class="op">)</span>, df<span class="op">=</span><span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">k</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]
intrcpt 0.7805314</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">probOS</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html" class="external-link">pt</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">log</a></span><span class="op">(</span><span class="fl">1.5</span><span class="op">)</span> <span class="op">-</span> <span class="va">mu</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">tau2</span><span class="op">+</span><span class="va">sigma2</span><span class="op">)</span>, df<span class="op">=</span><span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">k</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<p>We can also estimate this probability by means of simulation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Simulate 100000 new studies</span></span>
<span><span class="va">Nsim</span> <span class="op">&lt;-</span> <span class="fl">1000000</span> </span>
<span><span class="va">HRsim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="va">mu</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/TDist.html" class="external-link">rt</a></span><span class="op">(</span><span class="va">Nsim</span>, df<span class="op">=</span><span class="op">(</span><span class="va">resREML</span><span class="op">$</span><span class="va">k</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">tau2</span><span class="op">+</span><span class="va">sigma2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html" class="external-link">sum</a></span><span class="op">(</span><span class="va">HRsim</span><span class="op">&gt;</span><span class="fl">1.5</span><span class="op">)</span><span class="op">/</span><span class="va">Nsim</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.780329</code></pre>
</div>
</div>
<p>The probability is 78% , suggesting that using HER2 will often provide adequate discrimination.</p>
</section><section class="level2" data-number="2.6"><h3 data-number="2.6" id="multivariate-meta-analysis">
<span class="header-section-number">2.6</span> Multivariate meta-analysis<a class="anchor" aria-label="anchor" href="#multivariate-meta-analysis"></a>
</h3>
<p>In previous section, we used 14 of the 16 identified studies to evaluate the prognostic effect of HER2 on overall survival. Two studies were excluded from the meta-analysis because they did not provide direct evidence about overall survival. This is unwelcome, especially if the participants are otherwise representative of the population, clinical settings, and condition of interest <span class="citation" data-cites="riley_multivariate_2017">(<a href="#ref-riley_multivariate_2017" role="doc-biblioref">Riley and White 2017</a>)</span>. For this reason, we here discuss how multivariate meta-analysis methods can be used to include studies that do not necessarliy provide direct evidence on the outcome of interest. Briefly, multivariate meta-analysis methods simultaneously analyse multiple outcomes, which allows more studies to contribute towards each outcome.</p>
<p>For instance, 6 studies in the review of <span class="citation" data-cites="zhang_prognostic_2015">Zhang and Sun (<a href="#ref-zhang_prognostic_2015" role="doc-biblioref">2015</a>)</span> assessed the relation between HER2 and PFS. The corresponding hazard ratios are given below:</p>
<p>We can therefore combine this evidence with the HRs on overall survival to obtain more accurate estimates for the prognostic value of the hormone receptor HER2 with respect to PFS <em>and</em> OS.</p>
<p>The hormone receptor HER2 also has prognostic value for progression-free survival. Furthermore, the reported HRs appear to be much more homogeneous across studies.</p>
<p>Perform a random-effects meta-analysis and construct a forest plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">resPFS</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html" class="external-link">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">logHR</span>, sei <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">se.logHR</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">outcome</span><span class="op">==</span><span class="st">"PFS"</span><span class="op">)</span>, </span>
<span>              method <span class="op">=</span> <span class="st">"REML"</span>, slab <span class="op">=</span> <span class="va">Zhang</span><span class="op">$</span><span class="va">Study</span><span class="op">)</span></span>
<span><span class="va">resPFS</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 6; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0282 (SE = 0.1450)
tau (square root of estimated tau^2 value):      0.1679
I^2 (total heterogeneity / total variability):   11.43%
H^2 (total variability / sampling variability):  1.13

Test for Heterogeneity:
Q(df = 5) = 4.8450, p-val = 0.4351

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub
  0.8147  0.2008  4.0565  &lt;.0001  0.4211  1.2083  ***

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">metafor</span><span class="fu">::</span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/forest.html" class="external-link">forest</a></span><span class="op">(</span><span class="va">resPFS</span>, transf <span class="op">=</span> <span class="va">exp</span>, xlab <span class="op">=</span> <span class="st">"Hazard Ratio"</span>, refline <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div>
<div class="cell-output-display">
<div>
<figure><p><img src="ma-pf_files/figure-html/unnamed-chunk-22-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that the univariate meta-analysis for PFS is based on merely 6 studies, and that the univariate meta-analysis for OS was based on 14 studies. We can now employ multivariate meta-analysis to ‘’borrow information’’ from the 4 studies that report prognostic effects for both PFS and OS (Togami 2012, Mori 2010, Jongen 2009-2 and Backe 1997). This, in turn, allows all studies to contribute on the summary effect for HER2 in both outcomes.</p>
<p>Before we can proceed with the model fitting, we need to construct the full (block-diagonal) variance-covariance for all studies from the two outcomes. We can do this using the <code><a href="https://rdrr.io/r/base/diag.html" class="external-link">diag()</a></code> function in one line of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">V</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html" class="external-link">diag</a></span><span class="op">(</span><span class="va">Zhang</span><span class="op">$</span><span class="va">se.logHR</span><span class="op">**</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
</div>
<p>A multivariate random-effects model can now be used to meta-analyze the two outcomes simultaneously.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">res.MV</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.mv.html" class="external-link">rma.mv</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">logHR</span>, <span class="va">V</span>, mods <span class="op">=</span> <span class="op">~</span> <span class="va">outcome</span> <span class="op">-</span> <span class="fl">1</span>, random <span class="op">=</span> <span class="op">~</span> <span class="va">outcome</span> <span class="op">|</span> <span class="va">Study</span>, </span>
<span>                 struct <span class="op">=</span> <span class="st">"UN"</span>, data <span class="op">=</span> <span class="va">Zhang</span>, method <span class="op">=</span> <span class="st">"REML"</span><span class="op">)</span></span>
<span><span class="va">res.MV</span></span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Multivariate Meta-Analysis Model (k = 20; method: REML)

Variance Components:

outer factor: Study   (nlvls = 16)
inner factor: outcome (nlvls = 2)

            estim    sqrt  k.lvl  fixed  level
tau^2.1    0.0865  0.2942     14     no     OS
tau^2.2    0.0770  0.2775      6     no    PFS

     rho.OS  rho.PFS    OS  PFS
OS        1              -    4
PFS  1.0000        1    no    -

Test for Residual Heterogeneity:
QE(df = 18) = 33.7664, p-val = 0.0135

Test of Moderators (coefficients 1:2):
QM(df = 2) = 35.6315, p-val &lt; .0001

Model Results:

            estimate      se    zval    pval   ci.lb   ci.ub
outcomeOS     0.6704  0.1318  5.0868  &lt;.0001  0.4121  0.9287  ***
outcomePFS    0.8734  0.2151  4.0606  &lt;.0001  0.4518  1.2950  ***

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The new summary estimate is 0.670 (versus 0.667 ) with an SE of 0.132 (versus 0.135 ). Hence, we have gained some precision.</p>
<p>The new summary estimate is 0.873 (versus 0.815 ) with an SE of 0.215 (versus 0.201 ). We have lost precision, possibly because the presence of between-study heterogeneity is now more apparent, thereby complicating estimation of the summary effect.</p>
<p>Note that estimation of between-study heterogeneity was difficult for progression-free survival due to the limited number of studies. In particular, we found <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>τ</mi><mn>2</mn></msup><annotation encoding="application/x-tex">\tau^2</annotation></semantics></math>= 0.028 with an SE of 0.145. In the multivariate meta-analysis, the estimated between-study variance for PFS was much larger (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msup><mi>τ</mi><mn>2</mn></msup><annotation encoding="application/x-tex">\tau^2</annotation></semantics></math>=0.077), and based on all 16 rather than merely 6 studies.</p>
<p>In summary, the multivariate meta-analysis approach is often helpful as it reduces the need to exclude relevant studies from a meta-analysis, thereby decreasing the risk of bias (e.g. due to selective outcome reporting) and potentially improving precision. As indicated by <span class="citation" data-cites="riley_multivariate_2017">Riley and White (<a href="#ref-riley_multivariate_2017" role="doc-biblioref">2017</a>)</span>, a multivariate meta-analysis of multiple outcomes is most beneficial when the outcomes are highly correlated and the percentage of studies with missing outcomes is large.</p>
</section></section><section class="section level2" data-number="3"><h2 class="unnumbered" data-number="3" id="references">
<span class="header-section-number">3</span> References<a class="anchor" aria-label="anchor" href="#references"></a>
</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-altman_systematic_2001" class="csl-entry" role="listitem">
Altman, D. G. 2001. <em>Systematic Reviews of Evaluations of Prognostic Variables</em>. BMJ 323 (7306): 224–28.
</div>
<div id="ref-altman_how_2011" class="csl-entry" role="listitem">
Altman, Douglas G., and J. Martin Bland. 2011. <em>How to Obtain the p Value from a Confidence Interval</em>. BMJ 343: d2304.
</div>
<div id="ref-debray_detecting_2018" class="csl-entry" role="listitem">
Debray, and Richard D. Riley. 2018. <em>Detecting Small-Study Effects and Funnel Plot Asymmetry in Meta-Analysis of Survival Data: A Comparison of New and Existing Tests</em>. Res. Syn. Meth. 9 (1): 41–50. doi:10.1002/jrsm.1266.
</div>
<div id="ref-riley_prognosis_2013" class="csl-entry" role="listitem">
Riley. 2013. <em>Prognosis Research Strategy (PROGRESS) 2: Prognostic Factor Research</em>. PLoS Medicine 10 (2): e1001380. doi:10.1371/journal.pmed.1001380.
</div>
<div id="ref-riley_reporting_2003" class="csl-entry" role="listitem">
Riley, and S. A. Burchill. 2003. <em>Reporting of Prognostic Markers: Current Problems and Development of Guidelines for Evidence-Based Practice in the Future</em>. Br. J. Cancer 88 (8): 1191–8. doi:10.1038/sj.bjc.6600886.
</div>
<div id="ref-riley_interpretation_2011" class="csl-entry" role="listitem">
Riley, and J. J. Deeks. 2011. <em>Interpretation of Random Effects Meta-Analyses</em>. BMJ 342 (feb10 2): d549–d549. doi:10.1136/bmj.d549.
</div>
<div id="ref-riley_multivariate_2017" class="csl-entry" role="listitem">
Riley, and Ian R. White. 2017. <em>Multivariate and Network Meta-Analysis of Multiple Outcomes and Multiple Treatments: Rationale, Concepts, and Examples</em>. BMJ 358 (September): j3932.
</div>
<div id="ref-sauerbrei_evidence-based_2006" class="csl-entry" role="listitem">
Sauerbrei, and Douglas G. Altman. 2006. <em>Evidence-Based Assessment and Application of Prognostic Markers: The Long Way from Single Studies to Meta-Analysis</em>. Communications in Statistics - Theory; Methods 35 (7): 1333–42. doi:10.1080/03610920600629666.
</div>
<div id="ref-tzoulaki_assessment_2009" class="csl-entry" role="listitem">
Tzoulaki, and John P. A. Ioannidis. 2009. <em>Assessment of Claims of Improved Prediction Beyond the Framingham Risk Score</em>. JAMA 302 (21): 2345–52. doi:10.1001/jama.2009.1757.
</div>
<div id="ref-zhang_prognostic_2015" class="csl-entry" role="listitem">
Zhang, and Jing Sun. 2015. <em>Prognostic Role of Hormone Receptors in Endometrial Cancer: A Systematic Review and Meta-Analysis</em>. World J Surg Oncol 13 (June): 208. doi:10.1186/s12957-015-0619-1.
</div>
</div>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Thomas Debray, Valentijn de Jong.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

    </footer>
</div>





  </body>
</html>
